import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/research/Header";
import { Main } from "../components/research/Main";
import { Footer } from "../components/research/Footer";
import { useEffect, useState } from "react";
import axios from "axios";
import { useSession } from "next-auth/react";
import { API_ENDPOINT } from "../constants";
import { ResearchContainer } from "../components/research/Container";

const Research: NextPage = () => {

  return (
    <div id="app">
      <Head>
        <title>Research</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="sr-only">감귤마켓 홈화면과 피드</h1>
      {typeof window !== 'undefined' && <ResearchContainer /> }
    </div>
  );
};

export default Research;
